services:
  - type: web
    name: simrs-billing-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        fromDatabase:
          name: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
        fromDatabase:
          name: SUPABASE_ANON_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: DATABASE_URL
